### ISSUE TITLE
frontend: check types against test and production environments in github actions pull request flow, comment results on pr

### ISSUE THREAD

**Issue by LeadingMoominExpert** [three-consulting/epoc-frontend#225]
There already is a yarn script for checking types against dev, we need one that tests the types against production too. Those scripts need to be run in github actions and commented on the pr. Something like
```yaml
- name: Check types
  id: validate_types
  run: |
    yarn validate-types-dev
    yarn validate-types-prod

- name: Comment results of typecheck to pr
  uses: actions/github-script@v6
  with:
    script: |
      github.rest.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: ${{ steps.validate_types.outputs.* }}
      })
```
Or something along those lines, triggered by [pull requests](https://github.com/three-consulting/epoc-backend/blob/main/.github/workflows/pull-request.yaml#L3-L8). Empty messages should not be commented so some if condition should be used. 
**!** Note: github api does not differentiate issues and pr's so commenting on an issue == commenting on a pr

Additional reading:
https://github.com/actions/github-script#comment-on-an-issue
https://docs.github.com/en/actions
